"""SDP answer generation and offer parsing for SIP."""

from __future__ import annotations

import dataclasses
import re

from frizzle_phone.rtp.stream import PAYLOAD_TYPE_TELEPHONE_EVENT

_RTPMAP_TELEPHONE_EVENT_RE = re.compile(r"a=rtpmap:(\d+)\s+telephone-event/")


@dataclasses.dataclass
class SdpOffer:
    """Parsed SDP offer with audio RTP endpoint info."""

    audio_port: int
    connection_address: str
    telephone_event_pt: int | None = None


def parse_sdp_offer(sdp: str) -> SdpOffer:
    """Extract audio port and connection address from an SDP offer."""
    audio_port = 0
    connection_address = "0.0.0.0"
    telephone_event_pt: int | None = None

    for line in sdp.splitlines():
        line = line.strip()
        if line.startswith("m=audio "):
            # RFC 4566 §5.14: m=<media> <port> <proto> <fmt> ...
            # <port> is the transport port for the media stream.
            parts = line.split()
            if len(parts) >= 2:
                audio_port = int(parts[1])
        elif line.startswith("c=IN IP4 "):
            # RFC 4566 §5.7: c=<nettype> <addrtype> <connection-address>
            # For unicast, connection-address is the IP of the data source/sink.
            # A trailing "/<ttl>" or "/<ttl>/<count>" may appear for multicast;
            # we strip everything after "/" to handle both cases.
            addr = line[len("c=IN IP4 ") :]
            connection_address = addr.split("/")[0].strip()
        elif m := _RTPMAP_TELEPHONE_EVENT_RE.match(line):
            # RFC 4733 §2.5.1.2: dynamic PT for DTMF telephone-event
            telephone_event_pt = int(m.group(1))

    return SdpOffer(
        audio_port=audio_port,
        connection_address=connection_address,
        telephone_event_pt=telephone_event_pt,
    )


def build_sdp_answer(server_ip: str, rtp_port: int = 10000) -> str:
    """Build an SDP answer offering PCMU (payload type 0).

    Structured per RFC 3264 §6: the answer MUST contain exactly the same
    number of m= lines as the offer, with the connection address and port
    indicating where the answerer wishes to receive media.
    """
    lines = [
        # RFC 4566 §5.1: version 0 is the only defined SDP version
        "v=0",
        # RFC 4566 §5.2: o=<username> <sess-id> <sess-version> <nettype>
        #   <addrtype> <unicast-address>
        # The origin line uniquely identifies this session description.
        # Per RFC 3264 §6, the o= line MUST differ from the offer since
        # the answer is generated by a different entity.
        f"o=frizzle 0 0 IN IP4 {server_ip}",
        # RFC 4566 §5.3: exactly one s= field required per session
        "s=frizzle-phone",
        # RFC 4566 §5.7: session-level c= provides the unicast address
        # where the answerer receives media (RFC 3264 §6.1)
        f"c=IN IP4 {server_ip}",
        # RFC 4566 §5.9: t=0 0 means the session is permanent (both
        # start and stop times are zero)
        "t=0 0",
        # RFC 4566 §5.14: m=<media> <port> <proto> <fmt>
        # Proto "RTP/AVP" = RTP under the Audio/Video Profile (RFC 3551).
        # Fmt "0" = static payload type for PCMU (RFC 3551 §6, Table 4:
        # PT 0 = PCMU, 8000 Hz, 1 channel)
        f"m=audio {rtp_port} RTP/AVP 0 {PAYLOAD_TYPE_TELEPHONE_EVENT}",
        # RFC 4566 §6 (a=rtpmap): maps PT 0 to PCMU/8000.
        # Not strictly required for static PTs, but RFC 3264 §6.1 says
        # the answer SHOULD contain rtpmap mappings for static types.
        # RFC 3551 §4.5.14: PCMU = G.711 mu-law, 8-bit samples at 8 kHz.
        "a=rtpmap:0 PCMU/8000",
        # RFC 4566 §6 (a=ptime): recommended packetization interval in ms.
        # 20 ms = 160 samples at 8 kHz, a standard PCMU frame size.
        "a=ptime:20",
        # RFC 4733 §2.5.1.2: telephone-event for DTMF digits 0-15
        f"a=rtpmap:{PAYLOAD_TYPE_TELEPHONE_EVENT} telephone-event/8000",
        f"a=fmtp:{PAYLOAD_TYPE_TELEPHONE_EVENT} 0-15",
        "",
    ]
    return "\r\n".join(lines)
