changelog:
  categories:
    - title: "🐛 Bug Fixes"
      labels: ["bug"]
    - title: "🚀 Enhancements"
      labels: ["enhancement"]
    - title: "📖 Documentation"
      labels: ["documentation"]
    - title: "🔧 Infrastructure"
      labels: ["ci"]
    - title: "Other Changes"
      labels: ["*"]
