version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      target: devcontainer
    command: sleep infinity
    network_mode: host
    volumes:
      - ..:/app:cached
